server.port=9090
server.servlet.context-path=/weixin

spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

spring.main.allow-bean-definition-overriding=true



spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

spring.resources.static-locations=classpath:/static/,file:${file.upload-dir}/

file.upload-dir=D:/upload
app.upload-dir=${file.upload-dir}
